Repository COS301-SE-2023/Pronto, pull requests merged in 2023-09, with the labels that each got.

#326 Mobile help menu fixes
  MobileApp/screens/Settings/HelpScreen.js
Labels: enhancement, front-end

#331 Timetable export
  MobileApp/assets/icons/downloadicon.png
  MobileApp/package-lock.json
  MobileApp/package.json
  MobileApp/screens/Timetable/ScheduleTable.js
  MobileApp/yarn.lock
Labels: enhancement, front-end, integration

#335 Testing and Navigation
  .github/workflows/Workflow.yaml
  MobileApp/Testing/Login/ConfirmEmail.test.js
  MobileApp/Testing/Login/PasswordCriteriaMessage.test.js
  MobileApp/Testing/Login/Register.test.js
  MobileApp/Testing/Login/ResetPassword.test.js
  MobileApp/Testing/Login/VerifyCode.test.js
  MobileApp/Testing/Login/Welcome.test.js
  MobileApp/Testing/Login/__snapshots__/Welcome.test.js.snap
  MobileApp/Testing/Notifications/NotificationPreferences.test.js
  MobileApp/Testing/Settings/About.test.js
  MobileApp/Testing/Settings/__snapshots__/About.test.js.snap
  MobileApp/Testing/Settings/__snapshots__/SettingsComponent.test.js.snap
  MobileApp/Testing/__mocks___/aws-amplify.js
  MobileApp/app.json
  MobileApp/assets/data/locationInfo.json
  MobileApp/package-lock.json
  MobileApp/package.json
  MobileApp/screens/Login/ConfirmEmail.js
  MobileApp/screens/Login/PasswordCriteriaMessage.js
  MobileApp/screens/Login/Register.js
  MobileApp/screens/Login/ResetPassword.js
  MobileApp/screens/Login/VerifyCode.js
  MobileApp/screens/Login/Welcome.js
  MobileApp/screens/Notifications/NotificationPreferences.js
  MobileApp/screens/Settings/About.js
  MobileApp/screens/Timetable/NavigationScreen.js
  MobileApp/yarn.lock
Labels: front-end, testing

#339 Mobile map styling
  MobileApp/assets/data/locationInfo.json
  MobileApp/screens/Notifications/NotificationPreferences.js
  MobileApp/screens/Timetable/NavigationScreen.js
Labels: enhancement, front-end

#359 Navigation Updated
  WebApp/src/LectureView/Edit Module/PostAccordion.js
Labels: front-end

#383 CI/CD Pipeline
  .github/workflows/Workflow.yaml
  .github/workflows/build-backend.yml
  MobileApp/Testing/Notifications/NotificationPreferences.test.js
  Readme.md
  WebApp/cypress.config.js
  WebApp/cypress/fixtures/example.json
  WebApp/cypress/support/commands.js
  WebApp/cypress/support/component-index.html
  WebApp/cypress/support/component.js
  WebApp/src/Authentication/Institution/ConfirmEmail.js
  WebApp/src/Institution View/AddLecturer/addCourse.js
  WebApp/src/__testing__/AddLecturer.test.js
  WebApp/src/__testing__/DragAndDrop.test.js
  WebApp/src/__testing__/Institution/ConfirmEmail.test.js
  WebApp/src/__testing__/InstitutionNavigation.test.js
  WebApp/src/__testing__/addCourse.test.js
  WebApp/src/setupTests.js
  WebApp/test/unit/AddLecturer.test.js
  WebApp/test/unit/EditModule.test.js
  WebApp/test/unit/InstitutionNavigation.test.js
  WebApp/test/unit/LecturerNavigation.test.js
  WebApp/test/unit/PersonalInfo.test.js
  WebApp/test/unit/RecentAnnouncement.test.js
  WebApp/test/unit/postAccordion.test.js
  amplify/backend/package.json
  scripts/configure-amplify.sh
  scripts/initialise-amplify.sh
Labels: CI/CD

#386 Updated App ID
  scripts/initialise-amplify.sh
Labels: CI/CD

#420 Final documentation
  Documentation/Demo 4 documents/Architectural Requirements.pdf
  Documentation/Demo 4 documents/Code Quality Standards.pdf
  Documentation/Demo 4 documents/Demo 4 Slideshow.pptx
  Documentation/Demo 4 documents/Pronto Demo4 SRS.pdf
  Documentation/Demo 4 documents/Technical Installation.pdf
  Documentation/Demo 4 documents/Testing Policy.pdf
  Documentation/Demo 4 documents/User Manual.pdf
  Documentation/Diagrams/Architecture/Architechture.png
  Documentation/Diagrams/Architecture/NotificationsSystem.drawio.png
  MobileApp/assets/UserManualPages/UserManual-1.png
  MobileApp/assets/UserManualPages/UserManual-10.png
  MobileApp/assets/UserManualPages/UserManual-2.png
  MobileApp/assets/UserManualPages/UserManual-3.png
  MobileApp/assets/UserManualPages/UserManual-4.png
  MobileApp/assets/UserManualPages/UserManual-5.png
  MobileApp/assets/UserManualPages/UserManual-6.png
  MobileApp/assets/UserManualPages/UserManual-7.png
  MobileApp/assets/UserManualPages/UserManual-8.png
  MobileApp/assets/UserManualPages/UserManual-9.png
  MobileApp/assets/UserManualPages/UserManual.pdf
  Readme.md
  WebApp/src/Institution View/HelpFiles/AddLecturer.pdf
  WebApp/src/Institution View/HelpFiles/EditInfo.pdf
  WebApp/src/Institution View/HelpFiles/InstitutionInstructions.pdf
  WebApp/src/Institution View/HelpFiles/Schedule.pdf
  WebApp/src/Institution View/HelpFiles/StudentFiles.pdf
  WebApp/src/Lecturer View/HelpFiles/Announcements.pdf
  WebApp/src/Lecturer View/HelpFiles/EditModuleInfo.pdf
  WebApp/src/Lecturer View/HelpFiles/LecturerInstructions.pdf
  WebApp/src/Lecturer View/HelpFiles/PersonalInfo.pdf
Labels: documentation
