Repository COS301-SE-2023/Pronto, pull requests merged in 2023-07, with the labels that each got.

#170 Integration web s3
  Web view/Web app/src/Institution VIew/FileUpload/DragandDrop.js
  amplify/backend/api/pronto/schema.graphql
  amplify/backend/function/pronto5f713f59PostAuthentication/src/add-to-group.js
  amplify/backend/function/pronto5f713f59PreSignup/function-parameters.json
  amplify/backend/function/pronto5f713f59PreSignup/pronto5f713f59PreSignup-cloudformation-template.json
  amplify/backend/storage/prontoBlobeStore/cli-inputs.json
  amplify/cli.json
  amplify/team-provider-info.json
  src/ui-components/AdminCreateForm.d.ts
  src/ui-components/AdminCreateForm.jsx
  src/ui-components/AdminUpdateForm.d.ts
  src/ui-components/AdminUpdateForm.jsx
  src/ui-components/index.js
  src/ui-components/studioTheme.js
  src/ui-components/studioTheme.js.d.ts
  src/ui-components/utils.js
Labels: integration

#173 Style change to frontend
  Web view/Web app/src/Institution VIew/AddLecturer/addCourse.js
  Web view/Web app/src/Institution VIew/AddLecturer/addLecturer.js
Labels: front-end

#200 Select institution - Mobile App
  MobileApp/assets/data/universityInfo.json
  MobileApp/screens/Login/Register.js
  Web view/Web app/package.json
  Web view/Web app/src/Authentication/Lecturer/Login.js
  Web view/Web app/src/Authentication/Lecturer/styles.css
Labels: front-end

#242 Pre Auth Fix -- disabling autoconfrim
  amplify/backend/function/pronto5f713f59PreSignup/src/index.js
  amplify/backend/test/jest.config.js
Labels: backend

#249 Integration styling fixes
  MobileApp/assets/icons/files.png
  MobileApp/assets/icons/login.png
  MobileApp/assets/icons/reset-password.png
  MobileApp/components/NotificationList.js
  MobileApp/screens/FileView/FileView.js
  MobileApp/screens/Login/Login.js
  MobileApp/screens/Login/PasswordCriteriaMessage.js
  MobileApp/screens/Login/Register.js
  MobileApp/screens/Login/ResetPassword.js
  MobileApp/screens/Login/VerifyCode.js
  MobileApp/screens/Settings/DeleteAccount.js
  MobileApp/screens/Timetable/EditTimetable.js
  Web view/Web app/src/Authentication/Institution/ForgotPassword.js
  Web view/Web app/src/Authentication/Institution/Login.js
  Web view/Web app/src/Authentication/Lecturer/ForgotPassword.js
  Web view/Web app/src/Authentication/Lecturer/Login.js
Labels: front-end, integration

#259 Automation Integration
  .github/workflows/Workflow.yaml
  MobileApp/Testing/Notifications/NotificationList.test.js
  MobileApp/Testing/Search/SearchFilter.test.js
  MobileApp/Testing/Settings/SettingsComponent.test.js
  Web view/Web app/src/App.js
  Web view/Web app/src/__testing__/AddLecturer.test.js
  Web view/Web app/src/__testing__/DragAndDrop.test.js
  Web view/Web app/src/__testing__/InstitutionNavigation.test.js
  Web view/Web app/test/unit/AddLecturer.test.js
Labels: CI/CD
